### ISSUE TITLE
Wrong path to global node_modules on Windows

### ISSUE THREAD

**Issue by rmbaad** [tunnckoCore/npmls#2]
Hi!
I use npmls for getting list of node_modules and I have a problem with path to global modules.
npmls use global-prefix package and it's returned path to installed npm, but not to modules.
Real path to global node_modules on windows can be get by process.env.APPDATA.

I create pull request in global-prefix package, but I'm not sure this is the right decision.

**Comment by tadatuta** [comment]
Hey, the [PR](https://github.com/jonschlinkert/global-prefix/pull/5) was merged and new version of `global-prefix` was [released](https://github.com/jonschlinkert/global-prefix/releases/tag/0.1.3).

And it looks like to be installed automatically for new installations of `npmls` because of soft dependencies.

**Comment by tunnckoCore** [comment]
@kuksikus please report back if it's not fixed. This package just use `global-modules` and `global-prefix` behind the scenes, it not do anything special. It can't be what it it without them.
